version: '3.7'
services:
  db:
    container_name: inventory_db
    image: postgres:14.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory
    ports:
    - "5432:5432"
    volumes:
    - db-data:/var/lib/postgresql/data
volumes:
  db-data: